global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api-gestao-vagas"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"] #  host.docker.internal -> ip da maquina de execução dos containers
        labels:
          application: "api-gestao-vagas"