services:
  postgres:
    container_name: gestao_de_vagas_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_de_vagas
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonar:
    container_name: gestao_de_vagas_sonarqube
    image: sonarqube:9.9.0-community
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    networks:
      - application-network
    ports:
      - 9090:9090

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  prometheus_data:

networks:
  postgres-network:
    driver: bridge
  application-network:
    driver: bridge