version: '3.8'

services:
  postgres:
    container_name: gestao_de_vagas_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_de_vagas
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge 