version: '3.8'

services:
  postgres:
    container_name: gestao_de_vagas_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_de_vagas
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonar:
    container_name: gestao_de_vagas_sonarqube
    image: sonarqube:9.9.0-community
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions


volumes:
  postgres_data:
    name: postgres_data
    driver: local
  sonarqube_data:
    name: sonarqube_data
    driver: local
  sonarqube_logs:
    name: sonarqube_logs
    driver: local
  sonarqube_extensions:
    name: sonarqube_extensions
    driver: local

networks:
  postgres-network:
    name: postgres-network
    driver: bridge 