name: "Deploy to Production"

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: setup
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: 17
          - name: login docker
            run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          - name: build image
            run: cd spring-boot/gestao_de_vagas && docker build -t henryfranz/gestao_vagas .
          - name: push image
            run: docker push henryfranz/gestao_vagas
    deploy:
        runs-on: self-hosted
        needs: build 
        steps:
          - name: pull image
            run: docker pull henryfranz/gestao_vagas
          - name: remove container
            run: docker rm -f api
          - name: runner container
            run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} --name api henryfranz/gestao_vagas